__title__ = 'versionary'
__author__ = 'Devhouse Spindle'
__email__ = 'opensource@wearespindle.com'
__version__ = '0.4'
__copyright__ = 'Copyright (C) 2016 Devhouse Spindle'
__license__ = 'MIT License'
